name: Docs to HTML
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'readme.md'
      - 'media/**'

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_dir: /
          output_dir: html
          images_dir: /media
          # for example <img src="./images/file-name.png">
          image_import: ./media
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v3
        with:
          name: website
          path: html
